Metrics/LineLength:
  Max: 120

MethodLength:
  Max: 20

AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/*'
    - 'Guardfile'
    - 'spec/spec_helper.rb'
    - 'lib/tasks/**/*'
    - 'spec/factories/*'
    - !ruby/regexp /old_and_unused\.rb$/
