source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'mysql2'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'active_model_serializers'

group :development, :test do
  gem 'timecop'
  gem 'pry-rails'
  gem 'awesome_print'
  gem 'hirb'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.0'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'spork', '~> 1.0rc'
  gem 'rubocop', require: false
  gem 'guard-rubocop'
  gem 'annotate', '~> 2.6.6'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'simplecov'
  gem 'railroady'
  gem 'database_cleaner'
end
