# Parking example
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  database: parking_dev
  username: root
  password: Bender

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  database: parking_test
  username: root
  password: Bender

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8
  database: parking_prod
  username: root
  password: Bender
